#!/bin/sh
. "${CCG_COMPOSER_HOME}"/lib/lib.sh

http_proxy() {
    if [ "${CCG_HTTP_PROXY}" = "1" ]; then
        if [ "${HTTP_PROXY_HOST}x" = "x" ]; then
            HTTP_PROXY_HOST=${DOCKER_ROUTE}
        fi
        if [ "${HTTP_PROXY_HOST}x" = "x" ]; then
            warn  "CCG_HTTP_PROXY is set but I couldn't detect a proxy config. I tried HTTP_PROXY_HOST and then DOCKER_ROUTE. You can disable HTTP proxying by setting CCG_HTTP_PROXY=0"
            return
        fi
        http_proxy="http://${HTTP_PROXY_HOST}:3128"
        HTTP_PROXY="http://${HTTP_PROXY_HOST}:3128"
        NO_PROXY=${HTTP_PROXY_HOST}
        no_proxy=${HTTP_PROXY_HOST}
    fi
 
    export HTTP_PROXY http_proxy NO_PROXY no_proxy
}
