#!/bin/sh

info () {
    printf "\r  [\033[00;34mINFO\033[0m] %s\n" "$1" >&2
}
 
warn () {
    printf "\r  [\033[00;33mWARN\033[0m] %s\n" "$1" >&2
}
 
success () {
    printf "\r\033[2K  [\033[00;32m OK \033[0m] %s\n" "$1" >&2
}
 
fail () {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1" >&2
    echo '' >&2
    exit 1
}
