#!/bin/sh
. "${CCG_COMPOSER_HOME}"/lib/lib.sh

pip_proxy() {
    # pip default{
    PIP_INDEX_URL='https://pypi.python.org/simple'
    PIP_TRUSTED_HOST='127.0.0.1'
     
    if [ "${CCG_PIP_PROXY}" = "1" ]; then
        if [ "${PIP_PROXY_HOST}x" = "x" ]; then
            PIP_PROXY_HOST=${DOCKER_ROUTE}
        fi
        if [ "${PIP_PROXY_HOST}x" = "x" ]; then
            warn  "CCG_PIP_PROXY is set but I couldn't detect a pip proxy config. I tried PIP_PROXY_HOST and then DOCKER_ROUTE. You can disable PIP proxying by setting CCG_PIP_PROXY=0"
            return
        fi
        # use a local devpi install
        PIP_INDEX_URL="http://${PIP_PROXY_HOST}:3141/root/pypi/+simple/"
        PIP_TRUSTED_HOST="${PIP_PROXY_HOST}"
    fi
 
    export PIP_INDEX_URL PIP_TRUSTED_HOST
}
