sudo: required
matrix:
  fast_finish: true
services:
- docker
before_install:
- docker pull bioplatformsaustralia/bioplatforms-composer
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- chmod 755 ~/.docker
- chmod 644 ~/.docker/config.json
- export "GIT_BRANCH=$TRAVIS_BRANCH"
- test x"$TRAVIS_PULL_REQUEST_BRANCH" != x"" && export "GIT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH"
  || echo "This build is not a PR."
- export "BRANCH_NAME=$GIT_BRANCH"
- "./travis-build.sh"
- "./travis-prodbuild.sh"
env:
  global:
  - DOCKER_USERNAME: devredbox
  - secure: at4AfBP4ip3npaWBLcdAaHJCeSXciK3j0FRMbx2txrlpdRUtIqZwWuyA3kI07SN2TbYGJemyqqG7DqqSyWG3o+YQGF7IbEFYZrbji8qw6LZW+8ZWJXlm3ZXhuB626sjhTjYpoQF5VQzLYiTap+rxuhYLsSqK+jnR5X1weAuYNBfcmtceYk1SilTg+7GVg1qyM1ogLq5R24OY0t6PceFoDnZ0jwiV5UL5UttsBX42UFVI2+WfD9meg0at4uDmnxEIN41iyrGhQd4/cvbVtCj2X9eLZPAnrnKCjByqDDoBjAm6y34fd8odzCOUhZ5HA+aDTCwKihQXD4oN+c9yVg3wDvz37M1GbwPPUddGSyrKrqkcgra0g+HKzRDKE+oGUYdsVQWc4HyjGCEnaqyIewdajkSRttSpB9Ewf3wgHoMO5xgjALeFSXBOehUtYQfkLYFwkJxjCIq4LsPmMq2YqotnNI5zziWhtmSVxZ099snzhR9tVz84azi35R2MA3dPnSOPLORpeIWaKEG1Y5OVtEwAHIfIkmqaZAhxUoDsJUuer5RBLz7tiuKN3ROtkZ7Orol3JwS44YZg1YJQN1mudDB12sL5ZDMqOsMGrDRhKkDiQHAWig/5juPKUZcdksVUCjugDxRNR9xkmt/OxcVWQrEtfMm8wHk3I1I8BOVz4jQSa2c=
