version: '2'
services:

  dev:
    build:
      context: ./
      dockerfile: Dockerfile
    image: bioplatformsaustralia/bioplatforms-composer:${GIT_BRANCH}

  prod:
    build:
      context: ./
      dockerfile: Dockerfile
    image: bioplatformsaustralia/bioplatforms-composer:${BUILD_VERSION}
 
  latest:
    extends:
      file: docker-compose-build.yml
      service: prod
    image: bioplatformsaustralia/bioplatforms-composer:latest
