version: '2'
services:

  dev:
    build:
      context: ./
      dockerfile: Dockerfile
    image: muccg/ccg-composer:${GIT_BRANCH}

  prod:
    build:
      context: ./
      dockerfile: Dockerfile
    image: muccg/ccg-composer:${GIT_TAG}
 
  latest:
    extends:
      file: docker-compose-build.yml
      service: prod
    image: muccg/ccg-composer:latest
